### ISSUE TITLE
如果centerVC是个tabbarviewcontroller？

### ISSUE THREAD

**Issue by zhouzizi** [johnlui/SwiftSideslipLikeQQ#1]
如果centerVC是个tabbarviewcontroller,push要如何进行，以及手势如何做到全局。

**Comment by johnlui** [comment]
我没有用过 tabbarviewcontroller，不知道如何操作。:P

**Comment by xingfuqiu** [comment]
我也想知道,tabbarviewcontroller是怎么处理的

**Comment by johnlui** [comment]
加入 TabBar 的工作已经完成，正在写文章，稍后上传代码~

**Comment by johnlui** [comment]
代码已经更新，文章感觉略简单就先不写了哈哈~
